name: Check Website and Log

on:
  schedule:
    - cron: '* * * * *' # 每分钟执行一次

jobs:
  check_and_log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check website and save to log
      run: |
        curl https://balancer.eu.tankionline.com/balancer > website_content.txt
        git config --global user.name 'Your GitHub Username'
        git config --global user.email 'Your GitHub Email'
        git add website_content.txt
        git commit -m "Updated website content log"
        git push
