name: Tanki CN Checker

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '*/1 * * * *' # 每分钟执行一次

jobs:
  download_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Website Content
      run: |
        curl https://3dtank.com/datacenters.config.json > tanki_cn_content.txt

    - name: Setup Git Config
      run: |
        git config --global user.name 'Your GitHub Username'
        git config --global user.email 'Your GitHub Email'

    - name: Commit and Push
      run: |
        git add tanki_cn_content.txt
        git commit -m "Updated website content via schedule or manual trigger" -a || echo "No changes to commit"
        git push
