name: Check and Save JavaScript Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-and-save-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl

      - name: Check and save JavaScript files
        run: |
          for i in {1..9}; do
            url1="https://public-deploy$i.test-eu.tankionline.com/browser-public/index.html"
            url2="https://client-review-$i-public.test-ru.tankionline.com"
            
            # Fetch page source and extract JS URLs with 'main'
            js_urls1=$(curl -s "$url1" | grep -oP '<script[^>]+src="\K/browser-public/static/js/main\.[^"]+')
            js_urls2=$(curl -s "$url2" | grep -oP '<script[^>]+src="\K/client-review-[0-9]+-public/static/js/main\.[^"]+')
            
            # Loop through found JS URLs
            for js_url in $js_urls1 $js_urls2; do
              echo "Found JavaScript URL: $js_url"
              
              # Check if JS file already exists in the testanki1.github.io/test-sources directory
              if ! curl -s --head --fail "$url1$js_url" | grep "200 OK" > /dev/null; then
                echo "$js_url from $url1 does not exist, skipping."
              elif ! curl -s --head --fail "$url2$js_url" | grep "200 OK" > /dev/null; then
                echo "$js_url from $url2 does not exist, skipping."
              else
                # If not exists, save the JS file
                file_name=$(basename $js_url)
                output_path="./testanki1.github.io/test-sources/$file_name"
                
                curl -s "$url1$js_url" -o "$output_path"
                echo "Saved $js_url from $url1 to $output_path"
                
                curl -s "$url2$js_url" -o "$output_path"
                echo "Saved $js_url from $url2 to $output_path"
              fi
            done
          done
