name: Auto Sync Tanki Online Wiki

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 禁用默认的 GitHub Token 认证

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium googletrans==4.0.0-rc1 webdriver-manager
          pip install beautifulsoup4 lxml  # 安装 lxml 和 beautifulsoup4
          sudo apt update
          sudo apt install -y chromium-chromedriver  # 安装 Chromium 浏览器和 chromedriver

      - name: Run Wiki Scraper and Translator
        run: python scripts/wiki_scraper.py  # 执行爬取脚本

      - name: Check wiki directory
        run: ls -al wiki/  # 检查 wiki 目录是否有内容

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wiki/
          git commit -m "Auto update Tanki Online Wiki" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/testanki1/testanki1.github.io.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
